using UnityEngine;

public class Enemy : MonoBehaviour
{
   
    public GameObject explosionPrefab;
    private GameManager gameManager;

    private void Start()
    {
       gameManager = GameObject.Find("GameManager").GetComponent<GameManager>();    
    }
    // Update is called once per frame
    void Update()
    {
        transform.Translate(new Vector3(0, -1, 0) * Time.deltaTime * 8f);
        if (transform.position.y < -6.5f)
        {
            Destroy(this.gameObject);
        }
    }

    private void OnTriggerEnter2D(Collider2D whatDidIHit)
    {
      
        if (whatDidIHit.gameObject.tag == "Player")
       {
            whatDidIHit.GetComponent<PlayerController>().LoseALife();
            Instantiate(explosionPrefab, transform.position, Quaternion.identity);
            Destroy(this.gameObject);
        }
       else if (whatDidIHit.gameObject.tag == "Weapon")
        {
            Destroy(whatDidIHit.gameObject);
            Instantiate(explosionPrefab, transform.position, Quaternion.identity);
            gameManager.AddScore(5);
            Destroy(this.gameObject);
        }
    }
}

